name: My Workflow
on:
  issue_comment:
    types: [created]

jobs:
  my_first_job:
     runs-on: ubuntu-latest
     steps: 
     - uses: actions/checkout@v1
     - name: My first step
       uses: ./.github/actions/my-action.yml
